# Default values for oaebudt-dataspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # -- Global dataspace domain (required for ingress)
  domain: "michigan.oaebudt.think-it.io"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# OAEBUDT participant ID and DID configuration
participant:
  # The participant ID determines the name of the credentials to be added to the Identity Hub.
  # Therefore, the participant ID must match the folder name in the credentials' mount path.
  id: "participant-c"
  # For internal Kubernetes clusters, use a DID like did:web:did-service.oaebudt.svc.cluster.local,
  # where 'did-service' is the name of the Kubernetes service exposing the DID endpoint,
  # and 'oaebudt' is the namespace where the service and the connector are deployed.
  did: "did:web:did.participant-c.svc.cluster.local"

# Decentralized Claims Protocol configuration
dcp:
  tls:
    enabled: false
  # List of trusted DID issuers
  trustedIssuers:
    - "did:web:issuer.oaebudt.svc.cluster.local"
  identityHub:
    # -- Use a base64 key
    superuserKey: "c3VwZXItdXNlcg==.K+CKuM+8XNuEfLggseLntVljpgLnRzPMNo1WT6dWU1HUJP07l50k8AUreEIy3gcYTBn4vxzMWIg+1TDPYsxpug=="
    # The DID-related credentials are defined in a ConfigMap and mounted into the pod,
    # using the participant ID as a reference for both the ConfigMap name and the mount path.
    credentials:
      configMap: "{{ .Values.participant.id | lower }}-credentials"
      mountPath: "/etc/dataspace/did/credentials/{{ .Values.participant.id }}/"

# Federated catalog configuration
catalog:
  # Targets Nodes
  nodes:
    # Example node:
    #  - name: participant-b
    #    did: "did:web:did.participant-b.svc.cluster.local"
    - name: participant-c
      did: "did:web:did.participant-c.svc.cluster.local"
  crawler:
    # -- Initial delay for the crawling to start. Leave blank for a random delay
    initialDelay: 120
    # -- File path to a JSON file containing TargetNode entries
    targetsFile: "/etc/dataspace/participants.json"

# Connector endpoints configuration
endpoints:
  # Reports endpoint.
  report:
    port: 8100
    path: /api/report
    authType: "keycloak"
  # Default endpoint for incoming API calls.
  default:
    port: 7100
    path: /api
  # Provides access to the Federated Catalog for asset discovery; requires authentication.
  catalog:
    port: 7102
    path: /api/catalog
    authKey: "password"
  # Handles internal control operations such as contract negotiations and transfer processes.
  control:
    port: 7103
    path: /api/control
  # Manages data transfer protocol negotiations between connectors.
  protocol:
    port: 7104
    path: /api/dsp
  # Offers administrative control over the connector, including policies and assets; requires authentication.
  management:
    port: 7105
    path: /api/management
    authKey: "password"
  # Exposes information about the current version and build of the connector.
  version:
    port: 7106
    path: /api/version
  # Public endpoint for data retrieval when HTTP Pull is used; must be accessible from the internet.
  public:
    port: 17100
    path: /api/public
  # Resolves and interacts with Decentralized Identifiers (DIDs).
  did:
    port: 80
    path: /
  # Manages issuance and retrieval of Verifiable Credentials (VCs).
  credentials:
    port: 6102
    path: /api/credentials
  # Provides CRUD operations for Decentralized Identifiers (DIDs) and their documents.
  identity:
    port: 6103
    path: /api/identity
  # Enables clients to request credentials in the form of Verifiable Presentations (VPs) as defined by the DCP specification.
  presentation:
    port: 6104
    path: /api/presentation
  # Issues and validates security tokens for authenticated access within the Identity Hub.
  sts:
    port: 6106
    path: /api/sts

# This sets the container image
image:
  repository: 605134435349.dkr.ecr.us-east-1.amazonaws.com/oaebudt-dataspace/connector
  pullPolicy: IfNotPresent
  tag: "latest"

# This section is for setting up autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This is for setting Kubernetes Annotations to a Pod.
podAnnotations: {}

# This is for setting Kubernetes Labels to a Pod.
podLabels: {}

# This is for the secrets for pulling an image from a private repository
imagePullSecrets: []

# This section builds out the service account
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
  # Existing image pull secret bound to the service account to use to obtain the container image from private registries
  imagePullSecrets: []

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

livenessProbe:
  # Whether to enable kubernetes [liveness-probe]
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  # Whether to enable kubernetes [readiness-probes]
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# Resource management for the container
resources:
  limits:
    cpu: 1.5
    memory: 1536Mi
  requests:
    cpu: 500m
    memory: 1024Mi

# Node selector
nodeSelector: {}
# Tolerations
tolerations: []
# Affinity to configure which nodes the pods can be scheduled on
affinity: {}

service:
  # Service type to expose the running application on a set of Pods as a network service.
  type: ClusterIP
  labels: {}
  annotations: {}

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: ""
  annotations: []
  #  kubernetes.io/ingress.class: nginx
  #  kubernetes.io/tls-acme: "true"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# PostgreSQL chart configuration
postgresql:
  ## ref: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  # -- Switch to enable or disable the PostgreSQL helm chart
  install: true
  schema:
    # -- Enable auto-creation of the schema on boot
    autoCreate: true
  auth:
    postgresPassword: "oaebudt_postgres"
    # -- Database name must begin with a letter (a-z) or underscore (_)
    # -- Subsequent characters can be letters, digits (0-9), or underscores
    # -- Maximum name length is 31 characters by default
    database: "oaebudt_connector"
    # -- Username must begin with a letter (a-z) or underscore (_)
    # -- Subsequent characters can be letters, digits (0-9), or underscores
    # -- Maximum name length is 31 characters by default
    username: "oaebudt_connector"
    password: "oaebudt_connector"
  primary:
    initdb:
      scripts:
        # SQL script to initialize a second database and a user for Keycloak
        00_init_extensions.sql: |
          CREATE USER keycloak WITH PASSWORD 'keycloak';
          CREATE DATABASE keycloak OWNER keycloak;
          GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
      # The superuser credentials used to execute the initialization script
      user: "postgres"
      password: "oaebudt_postgres"

# HashiCorp Vault chart configuration
vault:
  ## ref: https://github.com/hashicorp/vault-helm/blob/main/values.yaml
  # -- Switch to enable or disable the HashiCorp Vault helm chart
  install: true
  injector:
    enabled: false
  server:
    standalone:
      enabled: true
  hashicorp:
    url: "http://{{ .Release.Name }}-vault:8200"
    timeout: 30
    tokenSecret: "{{ .Release.Name }}-vault-token"
    tokenSecretKey: "root-token"
    healthCheck:
      enabled: true
      standbyOk: true
    paths:
      secret: /v1/secret
      health: /v1/sys/health
      folder: ""

# MongoDB chart configuration
mongodb:
  ## ref: https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml
  # -- Switch to enable or disable the MongoDB helm chart
  install: true
  auth:
    rootUser: root
    rootPassword: "oaebudt_root"
    # User credentials for the database used by the report service (the backend)
    usernames:
      - "oaebudt_report"
    passwords:
      - "oaebudt_report"
    # The database name must be 'oaebudt' because it is currently hardcoded in the backend
    databases:
      - "oaebudt"

# Keycloak chart configuration
keycloak:
  ## ref: https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
  # -- Switch to enable or disable the Keycloak helm chart
  install: true
  postgresql:
    enabled: false
  auth:
    adminUser: admin
    adminPassword: "oaebudt_keycloak"
  # We template the database credentials into a secret and reference its keys here,
  # because if we used plain (non-secret) credentials, we couldn't dynamically inject them into values.yaml
  externalDatabase:
    existingSecret: "keycloak-db"
    existingSecretHostKey: "host"
    existingSecretPortKey: "port"
    existingSecretUserKey: "user"
    existingSecretDatabaseKey: "database"
    existingSecretPasswordKey: "password"
  # Importation of a participant's realm
  extraEnvVars:
    # Keycloak argument to import the realm at startup
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"
  # Mount the realm configuration from a ConfigMap
  extraVolumeMounts:
    - name: realm
      mountPath: "/opt/bitnami/keycloak/data/import"
      readOnly: true
  # Define the volumes from which the realm ConfigMap will be sourced
  extraVolumes:
    - name: realm
      configMap:
        name: "participant-realm"
        items:
          - key: "participant-realm.json"
            path: "michigan-realm.json"
  # Participant's realm configuration
  participantRealm:
    realm: "michigan"
    accessTokenLifespan: 3600
    clientSecret: "oaebudt-dataspace"
    username: "michigan"
    userPassword: "michigan-DS12345"
    userEmail: "michigan@oaebudt-ds.org"
    userFirstName: "Jeremy"
    userLastName: "Morse"
    userRealmRoles:
      - "user"
