version: '3.8'
name: oaeudt-mvd
services:
  # PostgreSQL instance for participant_a
  participant_a-db:
    image: postgres:17.4
    container_name: participant_a-db
    environment:
      POSTGRES_DB: participant_a
      POSTGRES_USER: participant_a
      POSTGRES_PASSWORD: participant_a
    ports:
      - "5432:5432"
    volumes:
      - participant_a_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - oaebudt-mvd

  # PostgreSQL instance for participant_b
  participant_b-db:
    image: postgres:17.4
    container_name: participant_b-db
    environment:
      POSTGRES_DB: participant_b
      POSTGRES_USER: participant_b
      POSTGRES_PASSWORD: participant_b
    ports:
      - "6432:5432"
    volumes:
      - participant_b_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - oaebudt-mvd

  # Vault instance for participant_a
  participant_a-vault:
    image: hashicorp/vault:1.18
    container_name: participant_a-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: participant_a
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - participant_a_vault_data:/vault/data
    networks:
      - oaebudt-mvd

  # Vault instance for participant_b
  participant_b-vault:
    image: hashicorp/vault:1.18
    container_name: participant_b-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: participant_b
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "9200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - participant_b_vault_data:/vault/data
    networks:
      - oaebudt-mvd

volumes:
  participant_a_data:
  participant_b_data:
  participant_a_vault_data:
  participant_b_vault_data:

networks:
  oaebudt-mvd:
    driver: bridge