global:
    domain: ENC[AES256_GCM,data:1Mugyj30B+LpMh8Ux0qgn6UKADRQMzWV5JTKvJPx0L4=,iv:w5UINhjy+GrgAs5PP1dSeyC10tOSHbF/jq6pl1AiLF4=,tag:PXNXcynbhjXt/mIX8tNIHg==,type:str]
participant:
    id: ENC[AES256_GCM,data:8SMzO3aru5UfXZqO,iv:JSvdHwFeUvEjKOI28U+O7JUjrOwCi72iw4gZngnrstI=,tag:l1GVk5i7l6ySOMQps1OrUg==,type:str]
    did: ENC[AES256_GCM,data:6s44BuplpTOAZNTvwXHkv9KBceW762khWttwxxbyllsMTErhFTpB2g==,iv:cGYklxMCX0SLzyGwqSVVFgtyiaI3/8G2zuObCLojz7w=,tag:iGWDAC3Oe0jy2a43Q/ko0A==,type:str]
dcp:
    trustedIssuers:
        - ENC[AES256_GCM,data:OqTAYhT58IkzcmXccPvnYpRESXVNEq91cDMGKMKjxBY5vg==,iv:EYXSlwv3ex9BD/8e4vzxAmagiUE7dwiczWxRXZFnhI8=,tag:904c5y8h89sT3EVsNvTaDw==,type:str]
    identityHub:
        superuserKey: ENC[AES256_GCM,data:3kGUWQf2GDdhegB5digfoI69jYeOVoxXk8yD/ieE5bQa+ffnVyVLCuvYLhWjvoeYdNPXhyZkNc62UrjTZ2yF49fD2oiOcG4rE1zBNlsEMwcGd951GXvBnAqOd497Sz51WPSmEZTsGrhY8V8OQAE6lZU=,iv:0hKg5oZrMP5wKktFpHfLdkB5yKJJaMFJL3IChYroTgw=,tag:7BgUq2zwmYMMO0Lp/57M7w==,type:str]
catalog:
    nodes:
        - name: ENC[AES256_GCM,data:peyxVvQ=,iv:6OU/U+mc8RO5J6g/o5T5hK+r0GL7cRLAemdlolTe2tY=,tag:jkh6TdpyafhFw1R87EG4Ew==,type:str]
          did: ENC[AES256_GCM,data:37kkVkaChV53RjI6HcIF8JXo21dT06s9lJm7USBpNWI2,iv:vgCwk6JxfSFHv19d3O9SQBRxon/TgHbxOLhEIQw1s5Y=,tag:WVPRpHbo0BpHTQkkxFOGlg==,type:str]
        - name: ENC[AES256_GCM,data:7t6qWs1T7Q==,iv:Nry4uPDsXuULaCDZPQr/tgtlzTxKm8VJq/qfYbiaE9s=,tag:RDdhCU8kR30kSV/i1Aag5g==,type:str]
          did: ENC[AES256_GCM,data:3InpLEZ2vqYGRQO+M+ExGt7rnmiGgLa8C83yBAvC/474Dm4=,iv:/BiLauzWp9Bl3uUSj3HLZW6YBbraj7h/PWnTVWWe2SY=,tag:HQJrVDX6WBj6VDZjQsf75Q==,type:str]
        - name: ENC[AES256_GCM,data:Z2dK9SQPzrnZ/GMzg1b+M+ha,iv:qPmG8j6EfGYFGSql6hAIdZtO5dz/fMHA57Px82b8Ing=,tag:K1gGajOccHMEvLpkVpE+bg==,type:str]
          did: ENC[AES256_GCM,data:0RHmXqKfiYM2EfbeususLUAJQWBjmk35KwNnhitxBnXDqmOsykwG3s+Eo1Th+Q==,iv:3LHSPr68m/2W4faDjqN4pnZGgioyzPV9t+t2v7b/f2g=,tag:6fyoaMU+xqVjoefdbVAcEQ==,type:str]
        - name: ENC[AES256_GCM,data:2K+my+r2PgU=,iv:+GtMLB3jTwdoedYI7iUgXGYfBQ+r5kkK3Gpw+Zo13cw=,tag:nvZXQxsoaBt0MCrW07mUOw==,type:str]
          did: ENC[AES256_GCM,data:FtCytuWmRExIlhUAtY1ZAJxXtw1KCNF/cVf8MCkDB4D3as29,iv:gyYinxQuV7uXACbGWMmew9+o7bmKbrppZ+yvG/raPao=,tag:VYJ7WraAt3z7qEiPtnhf7g==,type:str]
        - name: ENC[AES256_GCM,data:pzfdrbEvHfrtuOfb,iv:aeZ18dfwvmPGQcmdY1nsMqTlWdTTmEx12SoskUQFD7Y=,tag:Ih30WwDg9qXsjymTlCe6DA==,type:str]
          did: ENC[AES256_GCM,data:WKWvcDVovUfrigWqcntq8ZdshK2Ixb3n+02yd+jzV3a6qEFuRoswgA==,iv:BzQ1UpWw5QsbmqVWDJK4zJ3T+Y3SfFyBEl6AeOqHSk8=,tag:+rLqcQtvpjFm8fB50C1+5g==,type:str]
        - name: ENC[AES256_GCM,data:yHw3lmz8GFzfjdyXgQ==,iv:/nVx8KRMzfWcaMAHrTV1WLKLBnuT1k36v3FXQE9aUNI=,tag:+LbBvNhKwVAWpIU4+gm7jg==,type:str]
          did: ENC[AES256_GCM,data:QXOzWycqVTNTwaIFGMTiv/x12+UpeIBQsvoRwzZhY6Ndnv2LupRf3Kc=,iv:9aOVVXKv5EhD7llPeUqXktlu8FECKTvetvuLGVTl9pg=,tag:Jyl8nqiqwh08/HiiVGcsEA==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:sYCJTg==,iv:jA0q2Q0aWpi2LwuTpJzVzqdITTUcM3P/4fkXXaj5XhM=,tag:1hefzY+RgQoMW0uezEhvHA==,type:bool]
    className: ENC[AES256_GCM,data:X0US,iv:dhHdpcgFSkl+ZpDq7fJ9SKeyew0xKP1PcPTE3pM1S8I=,tag:avXLTQU/8xVcYBQAiGuEmw==,type:str]
    annotations:
        alb.ingress.kubernetes.io/listen-ports: ENC[AES256_GCM,data:E5NMoaWRkv83WJmCWILc9uSga589AJomKf25wsY=,iv:WS0cNHcLuHUL8stLpWnvxa4goQxx6JIUN1lFPXb73DM=,tag:/HzmRDh3AP8R5feC6tbBew==,type:str]
        alb.ingress.kubernetes.io/ssl-redirect: ENC[AES256_GCM,data:rXaE,iv:F4jP733tIhAyRlJmDxz+/sWFlwQdZfc34a+E4Otb+xc=,tag:cTda/bg0A2LIiN3+ZHZNRw==,type:str]
        alb.ingress.kubernetes.io/scheme: ENC[AES256_GCM,data:HaV56jR/U9kw20X17BiX,iv:Fs/MgA/f2zHHKzFyKFdEnAxkw75C+t9+g4U/qrA7SpQ=,tag:JS9ZrC8B/DEnUsBNppkNjw==,type:str]
        alb.ingress.kubernetes.io/target-type: ENC[AES256_GCM,data:qL4=,iv:8Xb76G2Xpi364WmoZhw7vpexGWlvPHsdOOXZ+VfrkUs=,tag:WtkF7UHZS5D/Egx9OsZokw==,type:str]
        alb.ingress.kubernetes.io/healthcheck-path: ENC[AES256_GCM,data:8keHnL2siaBLTqz7O5HHwMsqEA==,iv:8CtjIuvULajIG8RsJ8XwYsByraM+YYJ2v5zAPN/k4CU=,tag:N57+gk7ycwNvT7iY61VgBw==,type:str]
        alb.ingress.kubernetes.io/healthcheck-port: ENC[AES256_GCM,data:H58ksQ==,iv:HuHej5xvdQu9VuaRnvViVUt8Wn/jpHGLMQE843sJlRs=,tag:syD13iiD0soMcgoi8tBnqQ==,type:str]
        alb.ingress.kubernetes.io/group.name: ENC[AES256_GCM,data:9nwtnzkqTS3hII4+1+mj2cvgDQ==,iv:XzUS5G565IFcXXOidZMuMVCP53QKSDGMFyS2Q39DGjo=,tag:Tw9adrNs0RWEXI463HsgXA==,type:str]
vault:
    server:
        standalone:
            enabled: ENC[AES256_GCM,data:lbXv7w==,iv:OZzHL+O3CzjFu6UCN7bYD2ZscYDsnLICyQeBQ1PSGOY=,tag:Uf/mqhMhHHEqPcFhyg4Yaw==,type:bool]
            config: ENC[AES256_GCM,data:G2GZC3yKLjhTQ4bt5bPNv6iTDq0XeVclWFiLud9pPIhDbeVEgiDrsPXAX3VYixVyw0XpA06mS99uSkIsiir4bvw73g55lzPDI6eM0I4XIt2UMg7GycFEgpl4rV3U6kXzjcImYxLgABNVH1vmD/zKiHFf63oUZvv7K1GlqRvC3rE5mzoRAK73fa/5+dLpf57ffac96pwUrwEaNBaeSoTCwIGrXagrUK9G4nMSZINTZpVCF0CiyYiSFgHqXnxOPGJYtWXpjewHgcQwCW4yh01G+9B4iUJdTRalRef7bv+3fCvxjjOkMKT38Mb+xC3/MqBmFPXQx3K0aDI1rrateuMINK/CEVANxGPOTAevFki2H2p8ETF4OPg+9y/QgtYFi2TiYvwH2DiImDVvBgSE6hSpUIHinKz6Jzh8wDOe/undLJzIqO91G6Z7vC3j0iCMbKx+ztMWQqThetQPyEWlxApGwpc=,iv:97EyQL2NnzLTjQtCxRwghBOoRKas3H/XL+PAkGOcWh0=,tag:hPpHwzt40N0thQlQWiCUwg==,type:str]
keycloak:
    auth:
        adminUser: ENC[AES256_GCM,data:Iowf1aU=,iv:P9s+f3FtW8VfNIC2PXEAYkTVlflJXEZ/P4PfAHxi4A0=,tag:IBFFw7I8FC6DUsExbp3c2A==,type:str]
        adminPassword: ENC[AES256_GCM,data:JrBEbfCEihJn2eZt+Lel2bLooz4g4g==,iv:2JlGyXNXv+JxNrNKTCnAMXXusEzM5Pmxf4WCBMLRV8k=,tag:KNJh9ntamyfoh+RlA8WlVg==,type:str]
    participantRealm:
        realm: ENC[AES256_GCM,data:AF3l9N04W0lVOw7n,iv:hHXDdWKV/q4h9VNV1BAtBNKT3RxQ/Ge2NDcasKnIPq0=,tag:f6nAZBAuS/3g/U/IlVB/Gg==,type:str]
        accessTokenLifespan: ENC[AES256_GCM,data:l4zQCA==,iv:T3kF980CuKoDB8U7KV1pdLnERk0IQGGnHEuhR+Q8VB8=,tag:SdYqToCmAoaQlpT0H6Fr/Q==,type:int]
        username: ENC[AES256_GCM,data:rBmYxOJULtsL1uJe,iv:gieglTmgkj/uzXrywsimIkt42JeE0dt57RKZ5LDXAS0=,tag:auPT8hpk1XqLmX5C8KPTKg==,type:str]
        userPassword: ENC[AES256_GCM,data:el6aIhrHYDYv/DJL42k=,iv:1R//Z8DKvaUfCZ/5Nit7oKhv8lmyMth/BOYO+28J+M8=,tag:yYetvaQwxbgnDLhdESEgUg==,type:str]
        userEmail: ENC[AES256_GCM,data:38UXsGI3OpwRlMQ+UGeTk3Ooxt3u/6Rb,iv:+rN2g7PvP9EPy6099W67Bf2jrmYIeyEJwSGHdkExL9E=,tag:UYAcF7AwGLbJWUmWzsfnEA==,type:str]
        userFirstName: ENC[AES256_GCM,data:XfidrzhJTg==,iv:hEXmntDplM2LVR6S12p3kasbkx9gnJANEX0S/wHpmtU=,tag:mZYM7rpfSbDYGEnvP6At3Q==,type:str]
        userLastName: ENC[AES256_GCM,data:LGsW8w==,iv:WhpclDD+e8R/6M5w/C9Zl7KApNRBx89GzbDwjWWBdkQ=,tag:B7ROKG5fCzrd8A99vSTlgQ==,type:str]
        userRealmRoles:
            - ENC[AES256_GCM,data:dzgMvw==,iv:+C2ppgsdX2XkdbakscL+t2yeuEkEU2lqbhegctcEqBQ=,tag:HKgx1gglDZ/pupGUW9XcYQ==,type:str]
sops:
    age:
        - recipient: age189s8gx6f43q688c9gxfkye9zsjudjnxlm69u76zvrujx5r2rxy5s25duc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTjYzN2Z1SWtjMVlLQU9R
            SGdTZi9rbjBybFJtNkJVOWNxUmdMWjhpU0UwCkdMVm5saWlPM2tjVFNRSzdONWdT
            VWZtR3RDYjI0ZkxUR1ZHcy9tSXQ3WmsKLS0tIHV2Z2wyUjJZTnpWOTl4aERTZWc3
            ZFRDaGFqQXhacllOVGxSa25qN2ZoT0EKY85M5eQqzkSZVfFMppRA7DGeeJesJ7Zv
            V1UOzIv4E+wwk7yDWVGEEuHMSCCkRihyXLZt1fyYnYswPdwSXAeSQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T17:41:17Z"
    mac: ENC[AES256_GCM,data:Tc4HC08PTvyihcvS7Xhc5OL9fZnDzcHf+cTcT8zxXkfg/OVTpw4GZr1eL8AquePlS+3rQVphmqGNgxDNbeDzxDzJehnNP1uVocEG+JJr5YliF2FUaBehJQs/5RFRkX3okzjejKSE0CT4sIGykVmFZ+bK5M3JjOZ6EQi7hgi1ceU=,iv:Nvy0oTLBN2epcb5NQ+QkGceFaIYzJflnh90Evj21mk4=,tag:qYF17Sfg7sxch4xK5HveqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
