---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.dcp.identityHub.credentials.configMap . }}
  labels:
    {{- include "oaebudt-connector.labels" . | nindent 4 }}
data:
  dataprocessor-credential.json: | {{ .Values.dcp.verifiableCredentials.dataprocessor | trim |  nindent 4 }}
  membership-credential.json: | {{ .Values.dcp.verifiableCredentials.dataprocessor | trim |  nindent 4 }}
