---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.dcp.identityHub.credentials.configMap . }}
  labels:
    {{- include "oaebudt-connector.labels" . | nindent 4 }}
data:
  dataprocessor-credential.json: |
    {{- tpl ($.Files.Get (printf "credentials/%s/dataprocessor-credential.json" .Release.Namespace)) . | nindent 4 }}
  membership-credential.json: |
    {{- tpl ($.Files.Get (printf "credentials/%s/membership-credential.json" .Release.Namespace)) . | nindent 4 }}
