---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-target-nodes
  labels:
    {{- include "oaebudt-connector.labels" . | nindent 4 }}
data:
  {{- $targetsFilePath := .Values.catalog.crawler.targetsFile }}
  {{- $filename := regexReplaceAll "^.*/([^/]+)$" $targetsFilePath "$1" }}
  {{ $filename }}: |
    {
    {{- $length := len .Values.catalog.nodes }}
    {{- range $index, $participant := .Values.catalog.nodes }}
      "{{ $participant.name }}": "{{ $participant.did }}"{{- if lt (add $index 1) $length }},{{- end }}
    {{- end }}
    }
