apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  labels:
    {{- include "oaebudt-connector.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ printf "%s-postgresql" .Release.Name | b64enc | quote }}
  port: {{ "5432" | b64enc | quote }}
  user: {{ "keycloak" | b64enc | quote }}
  password: {{ "keycloak" | b64enc | quote }}
  database: {{ "keycloak" | b64enc | quote }}
