apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  labels:
    {{- include "oaebudt-connector.labels" . | nindent 4 }}
data:
  host: {{ printf "%s-postgres" .Release.Name | quote }}
  port: "5432"
  user: "keycloak"
  password: "keycloak"
  database: "keycloak"
