---
apiVersion: v1
kind: Secret
metadata:
  name: x-api-keys
  labels:
    {{- include "oaebudt-connector.labels" . | nindent 4 }}
data:
  superuser-key: {{ .Values.dcp.identityHub.superuserKey | b64enc | quote }}
