---
apiVersion: v1
kind: Service
metadata:
  name: public
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "oaebudt-connector.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: public
      protocol: TCP
      name: public
  selector:
    {{- include "oaebudt-connector.selectorLabels" . | nindent 4 }}
