name: oaeudt-mvd
services:
  # PostgreSQL instance for participant A
  participants-db:
    image: postgres:17.4
    container_name: participant-a-db
    environment:
      POSTGRES_DB: participant_a
      POSTGRES_USER: participant_a
      POSTGRES_PASSWORD: participant_a
    ports:
      - "5432:5432"
    volumes:
      - participants-db-data:/var/lib/postgresql/data
      - ./init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - oaebudt-mvd

  # Vault instance for participant A and B
  participants-vault:
    image: hashicorp/vault:1.18
    container_name: participants-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: participant_a_b
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - participants-vault-data:/vault/data
      - ./init/init-vault.sh:/init-vault.sh
    restart: unless-stopped
    networks:
      - oaebudt-mvd
    entrypoint:
      - sh
      - -c
      - 'apk add --no-cache openssl && vault server -dev & sleep 5 && sh /init-vault.sh && tail -f /dev/null'

volumes:
  participants-db-data:
  participants-vault-data:

networks:
  oaebudt-mvd:
    driver: bridge