name: oaeudt-mvd
services:
  # PostgreSQL instance for participant A
  participants-db:
    image: postgres:17.4
    container_name: participants-db
    environment:
      POSTGRES_DB: connector_a
      POSTGRES_USER: connector_a
      POSTGRES_PASSWORD: connector_a
    ports:
      - "5432:5432"
    volumes:
      - participants-db-data:/var/lib/postgresql/data
      - ./init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - oaebudt-mvd

  # Vault instance for participant A and B
  participants-vault:
    image: hashicorp/vault:1.18
    container_name: participants-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: participant_a_b
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./init/seed-vault.sh:/seed-vault.sh
    restart: unless-stopped
    networks:
      - oaebudt-mvd
    entrypoint:
      - sh
      - -c
      - 'apk add --no-cache openssl && vault server -dev & sleep 5 && sh /seed-vault.sh && tail -f /dev/null'
      
  # DID issuer 
  did-issuer:
    image: nginx:1.27-alpine
    container_name: did-issuer
    restart: unless-stopped
    ports:
      - "19999:80"
    volumes:
      - ./did-issuer/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./did-issuer/did.json:/var/www/.well-known/did.json:ro
    networks:
      - oaebudt-mvd

#   # Keycloak instance for participant A and B
#   participants-auth-api:
#     image: quay.io/keycloak/keycloak:26.1.4
#     container_name: participants-auth-api
#     environment:
#       KC_BOOTSTRAP_ADMIN_USERNAME: participant_a_b
#       KC_BOOTSTRAP_ADMIN_PASSWORD: participant_a_b
#       KC_DB: postgres
#       KC_DB_URL: jdbc:postgresql://participants-db/keycloak
#       KC_DB_USERNAME: keycloak
#       KC_DB_PASSWORD: keycloak
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./init/keycloak-realm.json:/opt/keycloak/data/import/realm-config.json
#     restart: unless-stopped
#     depends_on:
#       - participants-db
#     networks:
#       - oaebudt-mvd
#     command: ["start-dev", "--import-realm"]

volumes:
  participants-db-data:

networks:
  oaebudt-mvd:
    driver: bridge
