name: Connector build

on:
  push:
    branches:
      - "develop"
    paths:
      - "connector/**"
      - "!**.md"
      - "!docs/**"
  workflow_dispatch:  # Allow manual triggering

env:
  AWS_REGION: us-east-1
  AWS_OIDC_ROLE_TO_ASSUME: arn:aws:iam::605134435349:role/github-actions-assume-role
  ECR_REPOSITORY: oaebudt-dataspace/connector

jobs:
  build-push-connector:
    name: Build and Push Connector
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./connector  # Set default working directory for all run steps

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate short SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_TO_ASSUME }}
          role-session-name: github-actions-assume-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS credentials
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        env:
          IMAGE_TAG: ${{ steps.short-sha.outputs.sha }}
        with:
          context: ./connector
          file: ./connector/launchers/oaebudt-connector/Dockerfile
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.short-sha.outputs.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
