# This workflow builds the connector project and executes E2E tests using Gradle. It is triggered by pull request
# openings and synchronization, ensuring that the changes introduced by the PR are validated and do not break the
# connector's functionality.

name: Connector E2E Tests

on:
  pull_request:
    branches:
      - "develop"
    types:
      - opened
      - synchronize
    paths:
      - "connector/**"  # Trigger only if changes are made under the 'connector' directory
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-test:
    name: Build and Test Connector
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./connector  # Set default working directory for all run steps

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        run: ./gradlew build --info

      - name: Run E2E Tests
        run: ./gradlew test

      - name: Upload test results
        if: always()  # Run even if previous steps failed
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            connector/build/reports/tests/
            connector/build/test-results/
          retention-days: 7