name: Connector PR Validation

on:
  pull_request:
    branches:
      - "develop"
    types: [opened, reopened, synchronize]
    paths:
      - "connector/**"
      - "!**.md"
      - "!docs/**"
      - "!CODEOWNERS"
      - "!LICENSE"
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-test:
    name: Build and Test Connector
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./connector  # Set default working directory for all run steps

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build --info

      - name: Run E2E Tests
        run: ./gradlew test -DincludeTags="EndToEndTest"

      - name: Upload test results
        if: always()  # Run even if previous steps failed
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            connector/build/reports/tests/
            connector/build/test-results/
          retention-days: 7
